name: 'Git Tag Annotation'
description: 'Get the git annotation associated with the current tag'
inputs:
  sha:
    description: 'tag of interest (defaults to the GITHUB_REF environment variable)'
    required: false
outputs:
  git-message:
    description: 'The git tag annotation'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'git-commit'
  color: 'gray-dark'
